// <auto-generated />
using Fifa_WebAPI.DbContext;
using Fifa_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Fifa_WebAPI.Migrations
{
    [DbContext(typeof(FifaDbContext))]
    partial class FifaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fifa_WebAPI.Models.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("MatchDate");

                    b.Property<int?>("ScoreID");

                    b.Property<int?>("Team1ID");

                    b.Property<int?>("Team2ID");

                    b.HasKey("ID");

                    b.HasIndex("ScoreID");

                    b.HasIndex("Team1ID");

                    b.HasIndex("Team2ID");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Fifa_WebAPI.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("TeamID");

                    b.HasKey("ID");

                    b.HasIndex("TeamID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Fifa_WebAPI.Models.Score", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Contestant1");

                    b.Property<int>("Contestant2");

                    b.Property<int>("GoalsMadeByContestant1");

                    b.Property<int>("GoalsMadeByContestant2");

                    b.Property<int>("ScoreKind");

                    b.Property<int>("ScoreValue1");

                    b.Property<int>("ScoreValue2");

                    b.Property<int>("WhoWon");

                    b.HasKey("ID");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("Fifa_WebAPI.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TeamName");

                    b.HasKey("ID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Fifa_WebAPI.Models.Match", b =>
                {
                    b.HasOne("Fifa_WebAPI.Models.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreID");

                    b.HasOne("Fifa_WebAPI.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1ID");

                    b.HasOne("Fifa_WebAPI.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2ID");
                });

            modelBuilder.Entity("Fifa_WebAPI.Models.Player", b =>
                {
                    b.HasOne("Fifa_WebAPI.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID");
                });
#pragma warning restore 612, 618
        }
    }
}
